name: dezire-notebook-backend

on: 
  push:
  
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: dezire
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: docker.io/dezire/notebook-backend:latest
